name: Lint, Minify and Build Bookmarklet

# Trigger the workflow only on pushes to the main branch,
# ignoring pushes that only affect dist/ files.
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'dist/**'

jobs:
  lint:
    name: Lint JavaScript
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run ESLint on the source file
      - name: Run ESLint
        run: npx eslint src/rgaa-unfold.js

  build:
    name: Minify and Commit JavaScript
    runs-on: ubuntu-latest
    needs: lint  # Ensure minification runs only after linting succeeds
    if: ${{ !contains(github.event.head_commit.message, '[auto]') }}  # Skip if it's an automated commit

    steps:
      # Step 1: Checkout the repository with write access
      - name: Checkout repository (with write access)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true  # <-- Fix to allow pushing

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Ensure dist directory exists
      - name: Ensure dist directory exists
        run: mkdir -p dist

      # Step 5: Minify the JavaScript source file
      - name: Minify JavaScript
        # For now, keep the minification safe for bookmarklets.
        # You can add --compress --mangle in the future if needed.
        run: npx terser src/rgaa-unfold.js -o dist/rgaa-unfold.min.js

      # Step 6: Generate the bookmarklet version
      - name: Generate bookmarklet file
        run: |
          echo -n "javascript:" > dist/rgaa-unfold.bookmarklet.js
          cat dist/rgaa-unfold.min.js >> dist/rgaa-unfold.bookmarklet.js

      # Step 7: Commit the generated files if there are changes
      - name: Commit dist files if changed
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add dist/
          git diff --cached --quiet || (git commit -m "Build dist files [auto]" && git push)
